### ISSUE TITLE
Exception message: java.lang.NoSuchFieldError: STONE

### ISSUE THREAD

**Issue by EldritchEnthusiast** [DenDragon23/LovecraftPlus#77]
### Description

Whenever I try to load the game this error keeps popping up 

### Expected behavior

I would like to receive help if it's something that can be fixed from my side.

### Cryptic Cosmos Version

MythosCraft-1.16.5-1.4.3-beta-all

### Forge Version

v36.1.65

### Minecraft Version

v1.16.5

### Relevant Assets

```markdown
---- Minecraft Crash Report ----
// Don't do that.

Time: 8/15/21 3:07 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3792/1684854630.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:320) [?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3573/230546403.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.65.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$446/353891891.call(Unknown Source) [forge-1.16.5-36.1.65.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.crypticcosmos.crypticcosmos.register.BlockRegistries.<clinit>(BlockRegistries.java:28) ~[?:1.4.3-beta] {re:classloading}
-- MOD crypticcosmos --
Details:
	Mod File: MythosCraft-1.16.5-1.4.3-beta-all.jar
	Failure message: Cryptic Cosmos (crypticcosmos) has failed to load correctly
		java.lang.NoSuchFieldError: STONE
	Mod Version: 1.4.3-beta
	Mod Issue URL: https://github.com/Team-Cryptic-Cosmos/Cryptic-Cosmos/issues
	Exception message: java.lang.NoSuchFieldError: STONE
Stacktrace:
	at com.crypticcosmos.crypticcosmos.register.BlockRegistries.<clinit>(BlockRegistries.java:28) ~[?:1.4.3-beta] {re:classloading}
	at com.crypticcosmos.crypticcosmos.CrypticCosmos.<init>(CrypticCosmos.java:54) ~[?:1.4.3-beta] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[?:36.1] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3065/2107873140.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3086/1872515144.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1819823448 bytes (1735 MB) / 2086666240 bytes (1990 MB) up to 4772593664 bytes (4551 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5120m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.65.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.65.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.65.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.65.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.65.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.65
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.65-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
		FpsReducer-forge-1.23-mc1.16.5.jar                |FPS Reducer                   |fpsreducer                    |1.23-mc1.16.5       |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.1.65-universal.jar                |Forge                         |forge                         |36.1.65             |CREATE_REG|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		geckolib-forge-1.16.5-3.0.44.jar                  |GeckoLib                      |geckolib3                     |3.0.44              |CREATE_REG|Manifest: NOSIGNATURE
		MythosCraft-1.16.5-1.4.3-beta-all.jar             |Cryptic Cosmos                |crypticcosmos                 |1.4.3-beta          |ERROR     |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.118.jar                          |Just Enough Items             |jei                           |7.7.1.118           |CREATE_REG|Manifest: NOSIGNATURE
	Crash Report UUID: 98b87cf4-abb5-4189-b6a7-053aecfbd925
```

**Comment by PugzAreCute** [comment]
Thanks, I will take a look into this.

**Comment by PugzAreCute** [comment]
This seems like the problematic line,
[Click to see the line](https://github.com/Cryptic-Cosmos/Cryptic-Cosmos/blob/a6c6803da4969d2dbadf661ba6a0e72884bef7b9/src/main/java/com/crypticcosmos/crypticcosmos/registries/BlockRegistries.java#L28)

@EldritchEnthusiast Can you confirm this is the latest build?

**Comment by EldritchEnthusiast** [comment]
Yes, it was version MythosCraft-1.16.5-1.4.3-beta-all that was updated on 7/17/2021

**Comment by PugzAreCute** [comment]
Huh, i will take a look into that.

**Comment by Corvus20** [comment]
Was just coming in to report this same issue. Glad its already being looking into.
